version: 2
jobs:
  job1:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: npm install
      - run: npm test

  job2:
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - run: cat README.md

workflows:
  version: 2
<<<<<<< HEAD
  one-and-two:
    jobs:
      - job1
      - job2

  two-and-three:
=======
  # parallel:
  #   jobs:
  #     - job1
  #     - job2
  serial:
>>>>>>> 06b0f91... feat: branch dev 2nd commit
    jobs:
      - job1:
          filters:
            branches:
              only: master
      - job2:
          requires:
            - job1
